### ISSUE TITLE
RN

### ISSUE THREAD

**Issue by avet-m** [jacobp100/technicalc-calculator#9]
Hello! I saw your [article](https://jacobdoescode.com/2020/10/09/react-native-bottom-sheets/) about react native bottom sheet, thank you for it. Do you have the complex example of the bottom sheet component?

**Comment by jacobp100** [comment]
Not yet! I do want to get round to writing it at some point

**Comment by jacobp100** [comment]
You can see the exact code from TechniCalc's bottom sheet here:

https://gist.github.com/jacobp100/d7b219d225fafe0b2a0d7c3859eadb69

I do plan a more formal open sourcing of the bottom sheet at some point. But this should already be sufficiently decoupled for you to dump these files in your project (you'll need to update the import for `util/useSize` though)

**Comment by avet-m** [comment]
@jacobp100 thank you) I will try to use it
